window.GHOST_WORDS = {
  animals: {
    easy: ["CAMEL","EAGLE","GECKO","HORSE","KOALA","LEMUR","MOOSE","OTTER","PANDA","SHARK","SNAKE","TIGER","WHALE","ZEBRA"],
    medium: ["BUFFALO","CHICKEN","DOLPHIN","GAZELLE","GORILLA","HAMSTER","LEOPARD","LOBSTER","OSTRICH","PENGUIN","RACCOON","SPARROW"],
    hard: ["ALLIGATOR","ARMADILLO","BUTTERFLY","CROCODILE","JELLYFISH","KANGAROOS","PORCUPINE","SALAMANDR","WOLVERINE"]
  },
  australia: {
    easy: ["BEACH","BILBY","CORAL","DINGO","EMU??"].filter(w => w.length === 5).concat(["KOALA","OPERA","REEFS","ULURU"]),
    medium: ["BRISBNE","BUSHMAN","COCKATU","DARLING","OUTBACKS","WALLABY"].filter(w => w.length === 7),
    hard: ["AUSTRALIA","BILLABONG","BUSHFIRES","KANGAROOS","PLATYPUSS"].filter(w => w.length === 9)
  },
  food: {
    easy: ["APPLE","BREAD","GRAPE","HONEY","LEMON","MANGO","OLIVE","PEACH","PIZZA","SALAD"],
    medium: ["AVOCADO","BISCUIT","BURRITO","CHICKEN","COCONUT","PANCAKE","POPCORN","SAUSAGE"],
    hard: ["BLUEBERRY","CHOCOLATE","CROISSANT","PINEAPPLE","RASPBERRY","SPAGHETTI"]
  },
  nature: {
    easy: ["CLOUD","EARTH","FLAME","OCEAN","PLANT","RIVER","STONE","STORM","WATER"],
    medium: ["CRYSTAL","GARDENS","ORCHARD","RAINBOW","SUNRISE","THUNDER"],
    hard: ["EVERGREEN","MOONLIGHT","MOUNTAINS","NIGHTFALL","RAINSTORM","SUNFLOWER","WATERFALL","WILDFIRES"]
  },
  mystery: {
    easy: ["BRAIN","CHAIR","DREAM","GHOST","GREEN","HOUSE","LIGHT","MOUSE","NIGHT","ROBOT","SMILE","SPACE","TABLE"],
    medium: ["ANCIENT","BALANCE","CAPTAIN","CHARMING","DIAMOND","FANTASY","FREEDOM","HARMONY","JOURNEY","KINGDOM","LANTERN","MACHINE","MYSTERY","PHANTOM","SHADOWS","SILENCE","SPIRIT","TREASURE","VICTORY","VILLAGE","WARRIOR","WHISPER","WINDOWS"],
    hard: ["ADVENTURE","AFTERGLOW","BRILLIANT","CELEBRATE","CHAMPIONS","DISCOVERY","ENCHANTED","FIRELIGHT","GHOSTLIKE","HARMONIES","HEADLIGHT","IMAGINARY","KNOWLEDGE","PLAYGROUND","QUICKSAND","SCARECROW","STARLIGHT","STORYBOOK","THUNDERER","TREASURED","UNDERPASS","WONDERFUL"]
  }
};
